version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5430:5430"
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_USER: postgres
      POSTGRES_DB: demo_voting

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:4000
    restart: always
    volumes:
      - .:/home/code
    links:
      - db:db
    ports:
      - "4000:4000"
    env_file:
      - ./conf/.env
    depends_on:
      - db

volumes:
  postgres_data: